version: '3.8'

services:
  web:
    build: .
    container_name: app-laravel
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - DB_HOST=db
      - DB_NAME=corrente_conta
      - DB_USERNAME=root
      - DB_PASSWORD=Blue@2021
      - DB_CHARSET=utf8mb4
    depends_on:
      - db

  db:
    image: mysql:8.0  # Aqui, uso a versão 8.0, uma versão estável e amplamente compatível
    container_name: mysql
    restart: always
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Blue@2021
      MYSQL_DATABASE: corrente_conta
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: Blue@2021
      PMA_ABSOLUTE_URI: http://localhost:8081/
    depends_on:
      - db

volumes:
  db_data:
